name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: ssh deployment
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.KEY }}
        script: |
            cd telex-tester
            git pull origin main
            sudo systemctl restart myapp.service


    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build
